# Generated by Django 6.1.1 on 2026-10-02 23:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='clubly_url',
            field=models.URLField(blank=True, validators=[django.core.validators.RegexValidator('^https://(www\\.)?clubly\\.org/[\\w-]+/?$', "Use your club's Clubly page, e.g. https://clubly.org/mathclubatucdavis")]),
        ),
    ]
