# Generated by Django 6.1.1 on 2026-10-02 23:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator('^[A-Z]{2,4}$', 'Use the subject code in capitals, e.g. ECS.')])),
                ('number', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{3}[A-Z]{0,2}$', 'Use the 3-digit number, e.g. 036A or 150.')])),
                ('title', models.CharField(max_length=200)),
                ('units', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
            ],
            options={
                'ordering': ['subject', 'number'],
                'constraints': [models.UniqueConstraint(fields=('subject', 'number'), name='unique_course_code', violation_error_message='This course is already in the catalog.')],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Fall 2026"', max_length=30, unique=True)),
                ('instruction_begins', models.DateField()),
                ('instruction_ends', models.DateField()),
                ('finals_begin', models.DateField(blank=True, null=True)),
                ('finals_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['instruction_begins'],
                'constraints': [models.CheckConstraint(condition=models.Q(('instruction_ends__gte', models.F('instruction_begins'))), name='term_instruction_ends_after_begins', violation_error_message='Instruction must end on or after the day it begins.'), models.CheckConstraint(condition=models.Q(('finals_end__gte', models.F('finals_begin'))), name='term_finals_end_after_begin', violation_error_message='Finals must end on or after the day they begin.')],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crn', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^\\d{5}$', 'A CRN is 5 digits.')], verbose_name='CRN')),
                ('section_code', models.CharField(blank=True, help_text='e.g. "A01"', max_length=4)),
                ('instructor', models.CharField(blank=True, max_length=100)),
                ('final_exam_start', models.DateTimeField(blank=True, null=True)),
                ('final_exam_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sections', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='courses.term')),
            ],
            options={
                'ordering': ['course__subject', 'course__number', 'section_code'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=100)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='courses.term')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('LEC', 'Lecture'), ('DIS', 'Discussion'), ('LAB', 'Lab'), ('SEM', 'Seminar'), ('OTH', 'Other')], default='LEC', max_length=3)),
                ('days', models.CharField(help_text='Days in order using M T W R F S U (R = Thursday), e.g. "MWF".', max_length=7, validators=[django.core.validators.RegexValidator('^M?T?W?R?F?S?U?$', 'Use days in order from MTWRFSU, e.g. "MWF" or "TR".')])),
                ('start_time', models.TimeField(help_text='Campus local time')),
                ('end_time', models.TimeField(help_text='Campus local time')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='courses.section')),
            ],
            options={
                'ordering': ['section', 'kind', 'start_time'],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='meeting_ends_after_start', violation_error_message='A meeting must end after it starts.'), models.CheckConstraint(condition=models.Q(('days__regex', '^M?T?W?R?F?S?U?$'), models.Q(('days', ''), _negated=True)), name='meeting_days_valid', violation_error_message='Use days in order from MTWRFSU, e.g. "MWF" or "TR".')],
            },
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('term', 'crn'), name='unique_crn_per_term', violation_error_message='A section with this CRN already exists for this term.'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('final_exam_end__gt', models.F('final_exam_start'))), name='section_final_ends_after_start', violation_error_message='The final exam must end after it starts.'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('term', 'date'), name='unique_holiday_per_term_date'),
        ),
    ]
