# Generated by Django 6.1.1 on 2026-10-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_enrollment'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='meeting',
            name='meeting_ends_after_start',
        ),
        migrations.RemoveConstraint(
            model_name='meeting',
            name='meeting_days_valid',
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='courses_meeting_ends_after_start', violation_error_message='It must end after it starts.'),
        ),
        migrations.AddConstraint(
            model_name='meeting',
            constraint=models.CheckConstraint(condition=models.Q(('days__regex', '^M?T?W?R?F?S?U?$'), models.Q(('days', ''), _negated=True)), name='courses_meeting_days_valid', violation_error_message='Use days in order from MTWRFSU, e.g. "MWF" or "TR".'),
        ),
    ]
