# Generated by Django 6.1.1 on 2026-10-02 23:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_meeting_meeting_ends_after_start_and_more'),
        ('organizations', '0002_organization_clubly_url'),
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.CharField(help_text='Days in order using M T W R F S U (R = Thursday), e.g. "MWF".', max_length=7, validators=[django.core.validators.RegexValidator('^M?T?W?R?F?S?U?$', 'Use days in order from MTWRFSU, e.g. "MWF" or "TR".')])),
                ('start_time', models.TimeField(help_text='Campus local time')),
                ('end_time', models.TimeField(help_text='Campus local time')),
                ('location', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(default='General meeting', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_meetings', to='organizations.organization')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='club_meetings', to='courses.term')),
            ],
            options={
                'ordering': ['term__instruction_begins', 'start_time'],
                'abstract': False,
                'constraints': [models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='scheduling_clubmeeting_ends_after_start', violation_error_message='It must end after it starts.'), models.CheckConstraint(condition=models.Q(('days__regex', '^M?T?W?R?F?S?U?$'), models.Q(('days', ''), _negated=True)), name='scheduling_clubmeeting_days_valid', violation_error_message='Use days in order from MTWRFSU, e.g. "MWF" or "TR".')],
            },
        ),
    ]
